In [5]:
#Libraries
import numpy as np

In [6]:
#Hand Generated Inputs, Weigths and Biases

X = [[1, 2, 3, 2.5],
     [2, 5, -1, 2],
     [-1.5, 2.7, 3.3, -0.8]]

weights1 = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases1 = [2, 3, 0.5] 

weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5] 

In [7]:
#Dense Layer Generating Class
class Layer_Dense:
    def __init__(self,n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

#ReLu Activation Function Class
class Activation_ReLu:
    def forward(self,inputs):
        self.output = np.maximum(0, inputs)

#Softmax Activation Function Class
class Activation_Softmax:
    def forward(self,inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims = True))
        probablities = exp_values / np.sum(exp_values, axis=1, keepdims = True)
        self.outputs = probablities

In [8]:
#Construction of 4 / 20 / 3 Shaped Dense Neural Network
layer1 = Layer_Dense(4, 20)
activation1 = Activation_ReLu() # Assigning ReLu activation function to first layer
layer2 = Layer_Dense(20, 3)
softmax_layer = Activation_Softmax() # Softmax Output activation function

#Feeding forward
layer1.forward(X)
activation1.forward(layer1.output) 
layer2.forward(activation1.output)
softmax_layer.forward(layer2.output)

#Outputs
print(softmax_layer.outputs)

[[0.28703982 0.32840022 0.38455996]
 [0.32975294 0.27475573 0.39549132]
 [0.31295311 0.31277415 0.37427274]]
